import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Link } from 'react-router-dom';
import { 
  Brain, 
  Search, 
  MessageSquare, 
  ShieldCheck, 
  Zap, 
  ArrowRight,
  TrendingUp,
  CheckCircle,
  Briefcase,
  Gem
} from 'lucide-react';

export default function HowItWorksPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4 relative overflow-hidden">
        <div className="absolute inset-0 gradient-hero opacity-5" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-primary/10 rounded-full blur-3xl opacity-30" />
        
        <div className="container mx-auto relative group">
          <div className="max-w-4xl mx-auto text-center">
            <Badge variant="secondary" className="mb-6 px-4 py-2">
              <SparkleIcon className="w-4 h-4 mr-2 text-primary fill-primary" />
              The AI-Assisted Journey
            </Badge>
            <h1 className="text-5xl md:text-7xl font-extrabold mb-6">
              Simplify the <span className="gradient-text">Complex</span>
            </h1>
            <p className="text-xl text-muted-foreground mb-10 max-w-2xl mx-auto">
              From initial vision to final delivery, SkillBridge uses intelligent automation 
              to ensure every project is built with precision and trust.
            </p>
          </div>
        </div>
      </section>

      {/* Interactive Tabs Section */}
      <section className="py-24 px-4 container mx-auto mb-20">
        <Tabs defaultValue="client" className="max-w-5xl mx-auto">
          <div className="flex flex-col items-center mb-12">
            <h2 className="text-3xl font-bold mb-8">Choose Your Perspective</h2>
            <TabsList className="grid w-80 grid-cols-2 p-1 bg-muted/50 rounded-2xl h-14">
              <TabsTrigger value="client" className="rounded-xl font-bold transition-all data-[state=active]:bg-white data-[state=active]:shadow-lg">For Clients</TabsTrigger>
              <TabsTrigger value="freelancer" className="rounded-xl font-bold transition-all data-[state=active]:bg-white data-[state=active]:shadow-lg">For Freelancers</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="client" className="space-y-12 outline-none">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div className="space-y-8">
                <StepItem 
                  num="01" 
                  title="Consult with AI" 
                  desc="Chat with our intelligent consultant. It asks the technical questions you might miss to define your exact needs."
                  icon={MessageSquare}
                />
                <StepItem 
                  num="02" 
                  title="Generate Roadmap" 
                  desc="Instantly receive a detailed project scope, milestones, and budget estimates generated by AI."
                  icon={Brain}
                />
                <StepItem 
                  num="03" 
                  title="Precision Matching" 
                  desc="Our engine matches you with the best-vetted talent who specifically excel in your project's tech stack."
                  icon={Search}
                />
              </div>
              <div className="glass p-8 rounded-[2rem] border-white/20 shadow-2xl relative overflow-hidden group">
                <div className="absolute inset-0 gradient-hero opacity-5 group-hover:opacity-10 transition-opacity" />
                <div className="relative z-10">
                  <h3 className="text-2xl font-bold mb-4">Client Focus</h3>
                  <ul className="space-y-4">
                    <li className="flex items-center gap-3">
                      <CheckCircle className="w-5 h-5 text-success" />
                      <span>Verified quality deliverables</span>
                    </li>
                    <li className="flex items-center gap-3">
                      <CheckCircle className="w-5 h-5 text-success" />
                      <span>Safe escrow payments</span>
                    </li>
                    <li className="flex items-center gap-3">
                      <CheckCircle className="w-5 h-5 text-success" />
                      <span>Real-time milestone tracking</span>
                    </li>
                  </ul>
                  <Button variant="hero" className="mt-8 w-full group" asChild>
                    <Link to="/signup">
                      Post Your Project
                      <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </Link>
                  </Button>
                </div>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="freelancer" className="space-y-12 outline-none">
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div className="space-y-8">
                <StepItem 
                  num="01" 
                  title="AI-Assisted Profile" 
                  desc="Showcase your best work. Our AI helps highlight your unique technical strengths to clients."
                  icon={TrendingUp}
                />
                <StepItem 
                  num="02" 
                  title="Smart Bidding & Matching" 
                  desc="Receive direct project invites or place competitive bids on projects that perfectly align with your professional skills and rates."
                  icon={Zap}
                />
                <StepItem 
                  num="03" 
                  title="Build & Get Paid" 
                  desc="Commit to scoped milestones. Once approved, funds are instantly released from our secure escrow."
                  icon={ShieldCheck}
                />
              </div>
              <div className="glass p-8 rounded-[2rem] border-white/20 shadow-2xl relative overflow-hidden group">
                <div className="absolute inset-0 gradient-hero opacity-5 group-hover:opacity-10 transition-opacity" />
                <div className="relative z-10">
                  <h3 className="text-2xl font-bold mb-4">Freelancer Advantage</h3>
                  <ul className="space-y-4">
                    <li className="flex items-center gap-3">
                      <CheckCircle className="w-5 h-5 text-success" />
                      <span>Zero low-ball proposals</span>
                    </li>
                    <li className="flex items-center gap-3">
                      <CheckCircle className="w-5 h-5 text-success" />
                      <span>Guaranteed payment security</span>
                    </li>
                    <li className="flex items-center gap-3">
                      <CheckCircle className="w-5 h-5 text-success" />
                      <span>Detailed roadmaps provided</span>
                    </li>
                  </ul>
                  <Button variant="hero" className="mt-8 w-full group" asChild>
                    <Link to="/signup?role=freelancer">
                      Find Expert Work
                      <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </Link>
                  </Button>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </section>

      {/* The AI Advantage Spotlight */}
      <section className="py-24 px-4 bg-muted/20 border-y">
        <div className="container mx-auto">
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="bg-background border-none shadow-sm p-2">
              <CardContent className="p-8 text-center space-y-4">
                <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary mx-auto flex items-center justify-center">
                  <Brain className="w-6 h-6" />
                </div>
                <h4 className="font-bold text-xl">Calculated Scoping</h4>
                <p className="text-muted-foreground">AI calculates complexity and provides market-driven budget estimates instantly.</p>
              </CardContent>
            </Card>
            <Card className="bg-background border-none shadow-sm p-2">
              <CardContent className="p-8 text-center space-y-4">
                <div className="w-12 h-12 rounded-xl bg-accent/10 text-accent mx-auto flex items-center justify-center">
                  <Briefcase className="w-6 h-6" />
                </div>
                <h4 className="font-bold text-xl">Talent Pairing</h4>
                <p className="text-muted-foreground">Our algorithms vet technical tests and past performance for every project match.</p>
              </CardContent>
            </Card>
            <Card className="bg-background border-none shadow-sm p-2">
              <CardContent className="p-8 text-center space-y-4">
                <div className="w-12 h-12 rounded-xl bg-success/10 text-success mx-auto flex items-center justify-center">
                  <Gem className="w-6 h-6" />
                </div>
                <h4 className="font-bold text-xl">Quality Gates</h4>
                <p className="text-muted-foreground">Automated check-ins ensure that deliverables stay aligned with the initial roadmap.</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-24 px-4 max-w-4xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-extrabold mb-4">Common Questions</h2>
          <p className="text-muted-foreground">Everything you need to know about getting started.</p>
        </div>
        
        <Accordion type="single" collapsible className="w-full space-y-4">
          <AccordionItem value="item-1" className="border px-6 rounded-2xl bg-card">
            <AccordionTrigger className="text-lg font-bold py-6">How accurate is the AI Scoping?</AccordionTrigger>
            <AccordionContent className="text-muted-foreground pb-6 leading-relaxed">
              Our AI is trained on successful project data across multiple industries. While it 
              provides a highly accurate technical or creative starting point, both clients 
              and freelancers have full control to fine-tune the roadmap as the project evolves.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-2" className="border px-6 rounded-2xl bg-card">
            <AccordionTrigger className="text-lg font-bold py-6">Is SkillBridge free to use?</AccordionTrigger>
            <AccordionContent className="text-muted-foreground pb-6 leading-relaxed">
              It is completely free to chat with our AI Consultant and generate a roadmap. We only 
              take a small service fee when a contract is successfully signed and payment is processed.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-3" className="border px-6 rounded-2xl bg-card">
            <AccordionTrigger className="text-lg font-bold py-6">How do escrow payments work?</AccordionTrigger>
            <AccordionContent className="text-muted-foreground pb-6 leading-relaxed">
              When a client hires a freelancer, the milestone amount is securely held by SkillBridge. 
              The funds are only released to the freelancer once the client clicks "Approve" on 
              the delivered work.
            </AccordionContent>
          </AccordionItem>
          
          <AccordionItem value="item-4" className="border px-6 rounded-2xl bg-card">
            <AccordionTrigger className="text-lg font-bold py-6">What types of work does SkillBridge support?</AccordionTrigger>
            <AccordionContent className="text-muted-foreground pb-6 leading-relaxed">
              Our AI Consultant is proficient in identifying requirements across all professional domains, 
              from software development and creative design to writing, marketing, and business strategy. 
              We specialize in matching experts across all major service categories.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </section>

      <Footer />
    </div>
  );
}

function StepItem({ num, title, desc, icon: Icon }: { num: string, title: string, desc: string, icon: any }) {
  return (
    <div className="flex gap-6 items-start group">
      <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-card border flex items-center justify-center font-bold text-lg group-hover:bg-primary group-hover:text-white transition-all shadow-sm">
        {num}
      </div>
      <div className="space-y-2">
        <h4 className="text-xl font-bold flex items-center gap-2">
          <Icon className="w-5 h-5 text-primary" />
          {title}
        </h4>
        <p className="text-muted-foreground leading-relaxed">
          {desc}
        </p>
      </div>
    </div>
  );
}

function SparkleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" />
      <path d="M5 3v4" />
      <path d="M19 17v4" />
      <path d="M3 5h4" />
      <path d="M17 19h4" />
    </svg>
  );
}